name: Flutter iOS Build

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      FLUTTER_CHANNEL: stable
      FLUTTER_VERSION: 3.32.8
      APP_IDENTIFIER: com.liuyihua.myapp
      APPLE_DEVELOPMENT_TEAM_ID: ${{ secrets.APPLE_DEVELOPMENT_TEAM_ID }}
      APPSTORE_API_JSON: ${{ secrets.APPSTORE_API_JSON }} # base64 编码后的 AuthKey.json 文件内容

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Decode AuthKey.json
        run: |
          echo "${{ secrets.APPSTORE_API_JSON }}" | base64 --decode > fastlane/AuthKey.json

      - name: Install dependencies
        run: flutter pub get

      - name: Install fastlane
        run: sudo gem install fastlane

      - name: Generate Certificates & Provisioning Profiles
        run: |
          cd fastlane
          fastlane ios dev_match

      - name: Build iOS IPA
        run: |
          flutter build ios --release --no-codesign

          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -allowProvisioningUpdates \
                     -archivePath $PWD/build/Runner.xcarchive archive

          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath $PWD/build/ipa
