name: Flutter iOS Build (Development)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-ios-dev:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Install Flutter
        run: |
          set -e
          export FLUTTER_HOME="$HOME/flutter"
          git clone --depth 1 -b stable https://github.com/flutter/flutter.git "$FLUTTER_HOME"
          echo "$FLUTTER_HOME/bin" >> $GITHUB_PATH
          export PATH="$FLUTTER_HOME/bin:$PATH"
          flutter --version
          flutter precache --ios
        env:
          DEVSHELL_DISABLE_PROMPT: "1"

      - name: Flutter pub get
        run: flutter pub get

      - name: Install Certificates
        run: |
          security create-keychain -p "" build.keychain
          security import ./certs/ios_development.p12 -k ~/Library/Keychains/build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ./certs/myapp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build IPA
        run: |
          flutter build ipa --export-method development

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-dev-ipa
          path: build/ios/ipa/*.ipa

      - name: Cleanup
        if: always()
        run: |
          rm -f ~/Library/Keychains/build.keychain || true
